# -*- coding: utf-8 -*-
"""Ejercicio_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOoYwwAmzZewz8RC9VBajfogzv3MT-aR
"""

# Algoritmo para determinar si un número es par o impar

num = int(input("Ingrese un número: "))

if num % 2 == 0:
    print("El número es par")
else:
    print("El número es impar")