# -*- coding: utf-8 -*-
"""Ejercicio_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NsBo-tKqQ5xeQDyD011GzwdQv5iy90D
"""

# Algoritmo para verificar si un número es múltiplo de otro

A = int(input("Introduce el primer número entero positivo: "))
B = int(input("Introduce el segundo número entero positivo: "))

if A <= 0 or B <= 0:
    print("Uno o ambos números están errados, deben ser números positivos.")

else:

    if A % B == 0:
        print(f"El número {A} es múltiplo de {B}")
    else:
        print(f"El número {A} no es múltiplo de {B}")