# -*- coding: utf-8 -*-
"""Ejercicio_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZ4vzfSO49fyHSIyJUi0xHFqQRZMiTdI
"""

# Algoritmo para ordenar tres números en forma ascendente

num_1 = float(input("Ingrese el primer número: "))
num_2 = float(input("Ingrese el segundo número: "))
num_3 = float(input("Ingrese el tercer número: "))

if num_1 < num_2 and num_1 < num_3:
    if num_2 < num_3:
        print(f"El orden ascendente es: {num_1}, {num_2}, {num_3}")
    else:
        print(f"El orden ascendente es: {num_1}, {num_3}, {num_2}")
elif num_2 < num_1 and num_2 < num_3:
    if num_1 < num_3:
        print(f"El orden ascendente es: {num_2}, {num_1}, {num_3}")
    else:
        print(f"El orden ascendente es: {num_2}, {num_3}, {num_1}")
else:
    if num_1 < num_2:
        print(f"El orden ascendente es: {num_3}, {num_1}, {num_2}")
    else:
        print(f"El orden ascendente es: {num_3}, {num_2}, {num_1}")