# -*- coding: utf-8 -*-
"""Ejercicio_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnxPVIBuRJvZ0sPFsa034yeeOohsYl8p
"""

# Algoritmo para convertir un número entre 1 y 10 en su representación en letras

num = int(input("Ingrese un número entre 1 al 10: "))

if 1 <= num <= 10:

    numeros_a_letras = {
        1: "Uno",
        2: "Dos",
        3: "Tres",
        4: "Cuatro",
        5: "Cinco",
        6: "Seis",
        7: "Siete",
        8: "Ocho",
        9: "Nueve",
        10: "Diez"
    }

    literal = numeros_a_letras[num]
    print(f"El número en letras es: {literal}")
else:
    print("El número no está comprendido entre 1 y 10.")