# -*- coding: utf-8 -*-
"""Ejercicio_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKM4oPQer136zAfYpfHtiBZhKK1TGmcE
"""

# Algoritmo para determinar si un número es positivo, negativo o cero

# Solicitar al usuario que introduzca un número

num = int(input("Introduce un número: "))

# Verificar si el número es positivo, negativo o cero

if num > 0:
    print("El número es positivo")
elif num < 0:
    print("El número es negativo")
else:
    print("El número es cero")